export const STATUS = {
  BAD_REQUEST: 400,
  FORBIDDEN: 403
};

export const LENGTH = {
  MIN_MESSAGE: 1,
  MAX_MESSAGE: 1000,
  MIN_CHANNEL_NAME: 1,
  MAX_CHANNEL_NAME: 20,
  MAX_MESSAGES_SHOWN: 50,
  MIN_PASSWORD: 6,
  MAX_PASSWORD: 200,
  MIN_NAMELENGTH: 1,
  MAX_NAMELENGTH: 50,
  HANDLE: 20,
  STANDUP: 0,
  MIN_RATE: 0,
  MAX_RATE: 1,
};

export const TYPE = {
  CHANNEL: 1,
  DM: 2,
};

export const INVALID = -1;
